// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UseCase.Db;

#nullable disable

namespace UseCase.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260831093448_ProjectAndUserChanges")]
    partial class ProjectAndUserChanges
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Projects", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectId"));

                    b.Property<string>("ProjectCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProjectId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("ProjectsUsers", b =>
                {
                    b.Property<int>("ProjectNameProjectId")
                        .HasColumnType("int");

                    b.Property<int>("UserNameUserId")
                        .HasColumnType("int");

                    b.HasKey("ProjectNameProjectId", "UserNameUserId");

                    b.HasIndex("UserNameUserId");

                    b.ToTable("ProjectsUsers");
                });

            modelBuilder.Entity("UseCase.Models.Feedback", b =>
                {
                    b.Property<int>("FeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeedbackId"));

                    b.Property<int?>("ApprovedByUser")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("FeedbackByUser")
                        .HasColumnType("int");

                    b.Property<string>("FeedbackStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Pending");

                    b.Property<int>("FeedbackToUser")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReviewdAt")
                        .HasColumnType("datetime2");

                    b.HasKey("FeedbackId");

                    b.HasIndex("ApprovedByUser");

                    b.HasIndex("FeedbackByUser");

                    b.HasIndex("FeedbackToUser");

                    b.HasIndex("ProjectId");

                    b.ToTable("Feedbacks", t =>
                        {
                            t.HasCheckConstraint("Feedback Rating Limit", "[Rating] >= 1 AND [Rating] <= 5");

                            t.HasCheckConstraint("Feedback Status", "[FeedbackStatus] IN ('Pending','Approved','Declined')");
                        });
                });

            modelBuilder.Entity("UseCase.Models.Users", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("DeptName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmpID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ProjectsUsers", b =>
                {
                    b.HasOne("Projects", null)
                        .WithMany()
                        .HasForeignKey("ProjectNameProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UseCase.Models.Users", null)
                        .WithMany()
                        .HasForeignKey("UserNameUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UseCase.Models.Feedback", b =>
                {
                    b.HasOne("UseCase.Models.Users", "ApprovedByUserId")
                        .WithMany()
                        .HasForeignKey("ApprovedByUser")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("UseCase.Models.Users", "FeedbackByUsersId")
                        .WithMany()
                        .HasForeignKey("FeedbackByUser")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("UseCase.Models.Users", "FeedbackToUsersId")
                        .WithMany()
                        .HasForeignKey("FeedbackToUser")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Projects", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApprovedByUserId");

                    b.Navigation("FeedbackByUsersId");

                    b.Navigation("FeedbackToUsersId");

                    b.Navigation("Project");
                });
#pragma warning restore 612, 618
        }
    }
}
